export const UPDATE_SEARCH = 'UPDATE_SEARCH';
export const ADD_GIF_SEARCH = 'ADD_GIF_SEARCH';
export const REMOVE_GIF_SEARCH = 'REMOVE_GIF_SEARCH';
export const API_ERROR = 'API_ERROR';
export const SEARCH_ERROR = 'SEARCH_ERROR';
